---

language: minimal

services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install -y git

# branches:
#   only:
#     - develop
#     - master

script:
  - docker build -t fragsoc/esports-bot .

deploy:
  provider: script
  script: bash docker-push.sh
