version: "3"
   
services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=Pass2020!
    ports: 
      - 5432:5432
  bot:
    build: .
    command: python main.py
    environment: 
      - DISCORD_TOKEN=NzIxMzA5OTQxMzY5MDEyMjg0.XuSqZg.43QDmd4xZkK9JdmAvp939LBMvq4
      - PG_HOST=192.168.0.11
      - PG_DATABASE=esportsbot
      - PG_USER=postgres
      - PG_PWD=Pass2020!
      - TWITCH_CLIENT_ID=**
      - TWITCH_CLIENT_SECRET=**
      - ENABLE_TWITTER=False
      - ENABLE_TWITCH=False
    volumes:
      - ./src/:/code
    depends_on:
      - db